vich_uploader:
    db_driver: orm

    mappings:
        oeuvre_image:
        # dossier envoi des images
            uri_prefix: /images/oeuvres
            upload_destination: '%kernel.project_dir%/public/images/oeuvres'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
