vich_uploader:
    db_driver: orm

    mappings:
        oeuvres_image:
        # dossier dans lequel on envoi les images
            uri_prefix: /'%app.path.oeuvres_images%'
        # Ou l'on souhaite envoyer les différents fichiers
            upload_destination: '%kernel.project_dir%/public%app.path.oeuvres_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
