easy_admin:
    design:
      brand_color: '#0099ff'
      menu:
        - label : 'Site'
          icon: 'jedi'
          children:
          - {entity: 'Oeuvres', icon: 'hammer'}
          - {entity: 'Categories', icon: 'list'}
