easy_admin:
  entities:
    Artiste:
        class : App\Entity\Artiste
        form:
              fields:
                  - {property: 'nom'}
                  - {property: 'prenom'}
                  - {property: 'biographie'}
                  - {property: 'date_naissance'}
        list:
          actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-info'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}