easy_admin:
  entities:
    Oeuvres:
        class : App\Entity\Oeuvres
        form:
          fields: 
            - {property: 'nom'}
            - {property: 'description'}
            - {property: 'date_creation'}
            - {property: 'categories'}
            - {property: 'images'}
        templates:
          edit: 'admin/oeuvres/edit.html.twig'
        list:
          actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-info'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}


